"""empty message

Revision ID: f34240fb2f0f
Revises: 
Create Date: 2021-04-23 20:12:48.211810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34240fb2f0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), server_default='', nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('electricity_t1', sa.Integer(), nullable=True),
    sa.Column('hot_water', sa.Integer(), nullable=True),
    sa.Column('cold_water', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flats')
    # ### end Alembic commands ###
